version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: America/Los_Angeles
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: CI
    open-pull-requests-limit: 5
