name: mac

on:
  push:
    branches:
      - '**' # Runs on push to any branch
    tags:
      - '*' # Runs on any tag push
  pull_request:
    branches:
      - main # Runs on pull requests targeting the main branch

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  build-mac:

    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.base_ref == 'main')
    runs-on: macos-26
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
    - name: setup
      run: |
        cd ../..
        git clone --depth 1 https://github.com/open-ephys/plugin-GUI.git --branch main
        cd plugin-GUI/Build && cmake -G "Xcode" ..
    - name: build
      run: |
        cd Build
        cmake -G "Xcode" ..
        xcodebuild -configuration Release
#    - name: test
#      run: cd build && ctest
    - name: deploy
      if: github.ref == 'refs/heads/main'
      env:
        ARTIFACTORY_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
        MACOS_CERTIFICATE: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        MACOS_CERTIFICATE_PWD: ${{ secrets.BUILD_CERTIFICATE_PWD }}
        MACOS_CERTIFICATE_NAME: ${{ secrets.BUILD_CERTIFICATE_NAME }}
        MACOS_CI_KEYCHAIN_PWD: ${{ secrets.PROD_MACOS_CI_KEYCHAIN_PWD }}
        PROD_MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_APPLE_ID }}
        PROD_MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_TEAM_ID }}
        PROD_MACOS_NOTARIZATION_PWD: ${{ secrets.PROD_MACOS_NOTARIZATION_PWD }}
        build_dir: "Build/Release"
        package: OpenEphysFFTW-mac
      run: |
        plugin_api=$(grep -rnw ../../plugin-GUI/Source -e '#define PLUGIN_API_VER' | grep -Eo "[0-9]*" | tail -1)
        tag=$(git describe --tags $(git rev-list --tags --max-count=1))
        new_plugin_ver=$tag-API$plugin_api

        mkdir shared
        cp -r $build_dir/*.dylib shared
        cp -r libs/macos/bin/* shared
        mkdir -p licenses
        cp -r libs/macos/share/fftw licenses/fftw

        # Turn our base64-encoded certificate back to a regular .p12 file
        printf '%s' "$MACOS_CERTIFICATE" | base64 --decode > certificate.p12

        # We need to create a new keychain, otherwise using the certificate will prompt
        # with a UI dialog asking for the certificate password, which we can't
        # use in a headless CI environment
        security create-keychain -p $MACOS_CI_KEYCHAIN_PWD build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p $MACOS_CI_KEYCHAIN_PWD build.keychain
        security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $MACOS_CI_KEYCHAIN_PWD build.keychain
        /usr/bin/codesign --force -s "$MACOS_CERTIFICATE_NAME" -v shared/libOpenEphysFFTW.dylib --deep --strict --timestamp --options=runtime
        for dependency in shared/libfftw3*.dylib; do
          /usr/bin/codesign --force -s "$MACOS_CERTIFICATE_NAME" -v "$dependency" --deep --strict --timestamp --options=runtime
        done

        /usr/bin/codesign -dv --verbose=4 shared/libOpenEphysFFTW.dylib

        zipfile=${package}_${new_plugin_ver}.zip
        zip -r -X $zipfile shared licenses
        curl --fail --show-error --retry 3 -H "X-JFrog-Art-Api:$ARTIFACTORY_ACCESS_TOKEN" -T "$zipfile" "https://openephys.jfrog.io/artifactory/OpenEphysFFTW-plugin/mac/$zipfile"
